#
# 
# Notes:
# - the SCons Python package must be installed using Python 2.x even if
#   testing Python 3.x. Scons is only required to build gpsd.

language: python

addons:
  apt:
    packages:
    - swig
    - python python-pip python-dev
    
python:
  - 2.7

  
branches:
  only:
    - master
    - develop

before_install:
  - pip${TRAVIS_PYTHON_VERSION} install --upgrade pip
  - pip${TRAVIS_PYTHON_VERSION} install --upgrade setuptools
  - pip${TRAVIS_PYTHON_VERSION} install --upgrade codecov
  - ls /usr/bin/pip*
  - /usr/bin/pip2 install --upgrade SCons
  
before_script:
  - cd $HOME
  - git clone git://git.savannah.nongnu.org/gpsd.git
  - cd gpsd
  - git checkout master && git pull origin master
  - scons export_shm=yes prefix=$HOME
  - scons install
  
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coverage

after_success:
  - codecov

# command to run tests, e.g. python setup.py test
script: 
  - cd $TRAVIS_BUILD_DIR/gpsdshm
  - swig -python shm.i
  - cd $TRAVIS_BUILD_DIR
  - CPATH=$HOME/include LIBRARY_PATH=$HOME/lib python${TRAVIS_PYTHON_VERSION} setup.py build_ext --inplace
  - python${TRAVIS_PYTHON_VERSION} `which nosetests` -v tests/
