language: python

addons:
  apt:
    packages:
    - swig
    
cache:
  directories:
  - $HOME/gpsd

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
  
branches:
  only:
    - master
    - develop

before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade codecov
  - pip install --upgrade SCons
  
before_script:
  - cd $HOME
  - [ -d gpsd ] || git clone git://git.savannah.nongnu.org/gpsd.git
  - cd gpsd
  - git checkout master && git pull origin master
  - scons export_shm=yes prefix=$HOME
  - scons install
  
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coverage

after_success:
  - codecov

# command to run tests, e.g. python setup.py test
script: 
  - cd $HOME/mjuenema/python-gpsdshm
  - make test
