language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
  
branches:
  only:
    - master
    - develop

before_install:
  - pip install codecov
  - apt-get update
  - apt-get install -qq swig
  - apt-get install -qq libgps-dev

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coverage

after_success:
  - codecov

# command to run tests, e.g. python setup.py test
script: make test
