language: python

addons:
  apt:
    packages:
    - swig
    
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6
  
branches:
  only:
    - master
    - develop

before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade codecov
  - pip install --upgrade SCons
  
before_script:
  - cd $HOME
  - git clone git://git.savannah.nongnu.org/gpsd.git
  - cd gpsd
  - git checkout master && git pull origin master
  - scons export_shm=yes prefix=$HOME
  - scons install
  
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coverage

after_success:
  - codecov

# command to run tests, e.g. python setup.py test
script: 
  - cd $TRAVIS_BUILD_DIR
  - CPATH=$HOME/include LIBRARY_PATH=$HOME/lib python${TRAVIS_PYTHON_VERSION} setup.py build_ext
  - CPATH=$HOME/include LIBRARY_PATH=$HOME/lib python${TRAVIS_PYTHON_VERSION} setup.py build_ext --inplace
  - python${TRAVIS_PYTHON_VERSION} `which nosetests` -v tests/
