language: python

addons:
  apt:
    packages:
    - swig

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
  
branches:
  only:
    - master
    - develop

before_install:
  - pip install pip
  - pip install setuptools
  - pip install codecov
  - pip install SCons
  
before_script:
  - cd $HOME
  - git clone git://git.savannah.nongnu.org/gpsd.git
  - cd gpsd
  - git checkout master && git pull origin master
  - scons export_shm=yes
  - scons install
  
cache:
  directories:
    - $HOME/gpsd

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coverage

after_success:
  - codecov

# command to run tests, e.g. python setup.py test
script: make test
