#
# 
# Notes:
# - the SCons Python package must be installed using Python 2.x even if
#   testing Python 3.x. Scons is only required to build gpsd.

language: python

addons:
  apt:
    packages:
    - swig
    - mercurial
    - chrpath
    - xmlto
    - ccache
    
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  
env:
  - GPSD_RELEASE=3.16
  - GPSD_RELEASE=3.15
  - GPSD_RELEASE=3.14
  - GPSD_RELEASE=3.13
  - GPSD_RELEASE=3.12
  - GPSD_RELEASE=3.11
  - GPSD_RELEASE=3.10
  - GPSD_RELEASE=3.9
  - GPSD_RELEASE=3.8
  - GPSD_RELEASE=3.7
  - GPSD_RELEASE=3.6
  - GPSD_RELEASE=3.5
  - GPSD_RELEASE=3.4
  - GPSD_RELEASE=3.3
  - GPSD_RELEASE=3.2
  - GPSD_RELEASE=3.1
  - GPSD_RELEASE=3.0
  
branches:
  only:
    - master
    - develop
    
cache:
  directories:
  - $HOME/scons
  - $HOME/gpsd
  - $HOME/.ccache

before_install:
  - cd $HOME 
  - test -d scons || hg clone https://bitbucket.org/scons/scons
  - cd scons
  - /usr/bin/python2 bootstrap.py build/scons
  - cd build/scons
  - /usr/bin/python2 setup.py install --prefix=$HOME
  - ls $HOME/bin $HOME
  - pip${TRAVIS_PYTHON_VERSION} install --upgrade pip
  - pip${TRAVIS_PYTHON_VERSION} install --upgrade setuptools
  - pip${TRAVIS_PYTHON_VERSION} install --upgrade codecov
  
before_script:
  - cd $HOME
  - test -d gpsd || git clone git://git.savannah.nongnu.org/gpsd.git
  - cd gpsd
  - git checkout release-$GPSD_RELEASE && git pull origin release-$GPSD_RELEASE
  - test "$GPSD_RELEASE" != "3.4" || rm -fv leapseconds.cache  # issue 18
  - /usr/bin/python2 $HOME/bin/scons export_shm=yes python=no manbuild=no qt=no leapfetch=no prefix=$HOME
  
install:
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coverage

after_success:
  - codecov

# command to run tests, e.g. python setup.py test
script: 
  - cd $TRAVIS_BUILD_DIR/gpsdshm
  - swig -python shm.i
  - cd $TRAVIS_BUILD_DIR
  - CPATH=$HOME/gpsd LIBRARY_PATH=$HOME/gpsd python${TRAVIS_PYTHON_VERSION} setup.py build_ext --inplace
  - python${TRAVIS_PYTHON_VERSION} `which nosetests` -v tests/
